env:
  global:
    - secure: j3sWidFJORA5R4CEYrt/tRHzPk3nAbuufHa6KGkfewIMtE9PcHOoZwpotBwYsBhAa7m7+jNRGWs0M6kIAWmjb1pnbFV9vPkPQxi8wY4SM2pyPTADHtqKqN0LLaqbQr8mM00xIaMD4xo3CMBJc+k0kzgtO/Cq4p6Szqa1rMY87lM=
    - secure: K5gO1kcBSR4bjVNBQzdq4X2qXeXWh3Vojt1sdHyUqOFwU0DMriPG60CgJ7O6L6ycWlo56IDEXRiOcjuTkow4qDbvPCrffXZ40CrBzrDx8BUmMBssVMC4+/pp4qMP6YG1RF1qTRYvVy0tH+fuYAdLNCLNgUdqUuiXq19LSsgKvUQ=
language: node_js
node_js: 7
sudo: false
